apiVersion: v1
kind: Service
metadata:
  name: ocsinventory-db
  namespace: {{ .Values.ocsinventory.namespace }}
  labels:
    app: ocsinventory-db
spec:
  selector:
    app: ocsinventory-db
  ports:
    - name: db
      port: 3306
      targetPort: 3306

