apiVersion: v1
kind: Service
metadata:
  name: ocsinventory-server
  namespace: {{ .Values.ocsinventory.namespace }}
  labels:
    app: ocsinventory-server
spec:
  selector:
    app: ocsinventory-server
  ports:
    - name: server
      port: 80
      targetPort: 80

